#@ge-sh
GET  http://localhost:3000/shifts HTTP/1.1

Content-Type: application/json
{
    "username":"rest",
    "password_hash":"1020304050"
}

###

#@po-sh
POST   http://localhost:3000/shifts HTTP/1.1

Content-Type: application/json
{
    "username":"rest",
    "password_hash":"1020304050"
}

###

#@pu-sh
PUT    http://localhost:3000/shifts HTTP/1.1

Content-Type: application/json
{
    "username":"rest",
    "password_hash":"1020304050"
}

###

#@de-sh
DELETE    http://localhost:3000/shifts HTTP/1.1

Content-Type: application/json
{
    "username":"rest",
    "password_hash":"1020304050"
}